### ISSUE TITLE
dxafinalreport.Rmd File not Found

### ISSUE THREAD

**Issue by laurvana** [arianaparquetteemory/finaldata550#4]
Hi Ariana, 

I am having trouble using the make command to generate your dxafinalreport.html file. I think this is because there is no dxafinalreport.Rmd file contained in the main project directory? Other than that your repository looks great and well organized!

Best,
Lauren

**Comment by arianaparquetteemory** [comment]
Hi Lauren, 
Thank you so much for bringing this to my attention - I just added the dxafinalreport.rmd to the repository.  I really appreciate it!

Best, 
Ariana

**Comment by laurvana** [comment]
Yay! It works perfectly now!

Lauren

**Comment by nati1515** [comment]
It worked correctly for me as well!
