### ISSUE TITLE
make install not running 

### ISSUE THREAD

**Issue by ujnamr** [arianaparquetteemory/finaldata550#7]
Hi Ariana,

When I tried running the `make install`, it didn't run. So, It tried running the report directly, which worked fine. I re-checked your Makefile. In the line specifying the command to be executed: Rscript -e "renv::restore(prompt=FALSE)", I believe it was double-spaced instead of using the tab key. When I tried running it after editing that line, it ran perfectly fine.

Great work on the project, otherwise!

Best,
Manju

**Comment by arianaparquetteemory** [comment]
thank you
