### ISSUE TITLE
issues with makefile

### ISSUE THREAD

**Issue by benkeser** [arianaparquetteemory/finaldata550#8]
A few issues remaining:

- there is no folder called `dxafinalreport` included in the github repo. This seems to be where the code is trying to put the final report.
- the `docker run` command is not correct. It is currently configured to do an interactive (`-it`) run of the container that opens a `bash` terminal. It should instead be written so that the report automatically builds.
- Also in the `docker run` command you should reference the tag of the image that is from dockerhub. See the final hint on canvas.

**Comment by arianaparquetteemory** [comment]
Thank you Dr. Benkeser! I added an empty directory called "report". Forgot to add earlier. I also changed the `docker run` command
