### ISSUE TITLE
remaining issues

### ISSUE THREAD

**Issue by benkeser** [arianaparquetteemory/finaldata550#9]
[these lines](https://github.com/arianaparquetteemory/finaldata550/blob/d554a2664e5e6567ada5bcf06978205643144c6e/makefile#L30-L31) are still not correct.
- please review Canvas hints again
- please remove dependency of the `make` command on `dxaimage`

**Comment by arianaparquetteemory** [comment]
Okay, should be good now. dxaimage is the tag on my image.

**Comment by benkeser** [comment]
I think you still have issues:
```
report/dxafinalreport.html: dxaimage 
    ddocker run -v "$$(pwd)/dxafinalreport:/report/dxafinalreport" arianaparquetteemory/finaldata550/dxaimage
```

should be

```
report/dxafinalreport.html: dxaimage 
    docker run -v "$$(pwd)/dxafinalreport:/report/dxafinalreport" arianaparquetteemory/finaldata550:dxaimage
```
